#ifndef JTOneFixTapClickSuppression_h
#define JTOneFixTapClickSuppression_h

#include <stdbool.h>
#include <stdint.h>
#include <stdatomic.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef enum {
    JTOneFixPointerEventNone = 0,
    JTOneFixPointerEventLeftDown,
    JTOneFixPointerEventLeftUp,
    JTOneFixPointerEventLeftDragged,
    JTOneFixPointerEventRightDown,
    JTOneFixPointerEventRightUp,
    JTOneFixPointerEventRightDragged,
    JTOneFixPointerEventOtherDown,
    JTOneFixPointerEventOtherUp,
    JTOneFixPointerEventOtherDragged,
} JTOneFixPointerEvent;

/*
 * Owns pointer events produced by macOS tap-to-click while a One-Fix Tap is in
 * progress. Down/up ownership is paired so an up event can never leak after
 * its down was consumed. A short post-release grace catches the delayed click
 * generated by the trackpad driver.
 */
typedef struct {
    atomic_bool contactOwned;
    atomic_uint_fast64_t suppressUntilNanos;
    atomic_bool leftPairOwned;
    atomic_bool rightPairOwned;
    atomic_bool otherPairOwned;
} JTOneFixTapClickSuppression;

#define JT_ONE_FIX_TAP_CLICK_SUPPRESSION_INITIALIZER \
    { ATOMIC_VAR_INIT(false), ATOMIC_VAR_INIT(0), \
      ATOMIC_VAR_INIT(false), ATOMIC_VAR_INIT(false), \
      ATOMIC_VAR_INIT(false) }

#define JT_ONE_FIX_TAP_CLICK_GRACE_NANOS UINT64_C(180000000)

void JTOneFixTapClickSuppressionReset(
    JTOneFixTapClickSuppression *suppression);

void JTOneFixTapClickSuppressionBegin(
    JTOneFixTapClickSuppression *suppression);

void JTOneFixTapClickSuppressionEnd(
    JTOneFixTapClickSuppression *suppression,
    uint64_t nowNanos);

bool JTOneFixTapClickSuppressionShouldSuppress(
    JTOneFixTapClickSuppression *suppression,
    JTOneFixPointerEvent event,
    uint64_t nowNanos);

#ifdef __cplusplus
}
#endif

#endif /* JTOneFixTapClickSuppression_h */
